<?php

require 'plugins/MetastazPlugin/lib/om/BaseMetastazTemplateFieldTypePeer.php';

/**
 * Skeleton subclass for performing query and update operations on the 'metastaz_template_field_type' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * lun. 19 sept. 2011 12:03:38 CEST
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.MetastazPlugin.lib
 */
class MetastazTemplateFieldTypePeer extends BaseMetastazTemplateFieldTypePeer {

} // MetastazTemplateFieldTypePeer
